### ISSUE TITLE
"IcameraControls" is inaccessible due to it's protection level

### ISSUE THREAD

**Issue by Oscar-Navarrete-Estevez** [jt28828/photobooth-app#1]
After cloning, when trying to build the android version of the photobooth, I get the error:

> "ICameraControls" is inaccessible due to it's protection level

I fixed it by adding _public_ property to the interface.
Do I have some setting wrong for me to have to this to make it work?

**Comment by jt28828** [comment]
Hi, 
I never fully finished the Android development side of the project due to time constraints before the event. The iOS project works as intended but I can't guarantee the Android project will even run because there's a lot of platform-specific code that would still need to be implemented to work the camera. Check out the iOS project if you want a reference for what needs to be done. (Finishing the camera preview view etc.) 

I may revisit this project at some point to finish it but I can't guarantee it'll be any time soon.
